services:
  agentia:
    container_name: agentia
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 2334:8501
    volumes:
      - ./data/agents:/app/agents:ro
      - ./data/.cache:/app/.cache
    env_file: .env