services:
  agentia:
    container_name: agentia
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${STREAMLIT_SERVER_PORT:-8501}:${STREAMLIT_SERVER_PORT:-8501}
    volumes:
      - ./data/agents:/app/agents
      - ./data/.cache:/app/.cache
    env_file: .env