services:
  agentia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentia
    restart: unless-stopped
    ports:
      - 2334:8501
    volumes:
      - ./agents:/app/agents
      - ./.cache:/app/.cache
    env_file: .env