services:
  agentia:
    container_name: agentia
    build:
      context: .
      dockerfile: Dockerfile
    image: wenyuzhao/agentia
    restart: unless-stopped
    ports:
      - ${SERVER_PORT:-8501}:8501
    volumes:
      - ./data/agents:/app/agents
      - ./data/.cache:/app/.cache
    environment:
      # Required environment variables
      OPENAI_API_KEY: ${OPENAI_API_KEY:?}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:?}
      # Environment variables for plugins
      # mstodo
      AUTH_AZURE_AD_CLIENT_ID: ${AUTH_AZURE_AD_CLIENT_ID:?}
      AUTH_AZURE_AD_CLIENT_SECRET: ${AUTH_AZURE_AD_CLIENT_SECRET:?}
      # search
      AUTH_DATAFORSEO_USERNAME: ${AUTH_DATAFORSEO_USERNAME:?}
      AUTH_DATAFORSEO_PASSWORD: ${AUTH_DATAFORSEO_PASSWORD:?}
      TAVILY_API_KEY: ${TAVILY_API_KEY:?}
      # gmail
      AUTH_GMAIL_CLIENT_ID: ${AUTH_GMAIL_CLIENT_ID:?}
      AUTH_GMAIL_CLIENT_SECRET: ${AUTH_GMAIL_CLIENT_SECRET:?}
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: &ignore
            - .*
            - _*
            - "**/__pycache__"
            - agents
        - action: rebuild
          path: pyproject.toml
        - action: restart
          path: .
          ignore: *ignore
