version = 1

[formatters]
default = { format = "[%(asctime)s][%(levelname)s][%(name)s] %(message)s" }

[handlers]
default = { class = "logging.StreamHandler", formatter = "default", stream = "ext://sys.stdout" }

[loggers]
agentia = { level = "INFO", handlers = ["default"] }
