name: Unit Tests

on: [push, pull_request]

jobs:
  tests:
    environment: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      - name: Install Packages
        run: |
          sudo apt-get install -y libomp-dev
          uv venv
          uv sync --all-extras --all-groups --frozen
      - name: Run PyTest
        run: uv run pytest
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
